# fly.toml app configuration file generated for njiuko-windmill-native-worker on 2024-01-16T16:19:14+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "njiuko-windmill-native-worker"
primary_region = "fra"

[build]
  image = "ghcr.io/windmill-labs/windmill-ee:1.342"

[env]
  BASE_URL = "https://njiuko-windmill-server.fly.dev/"
  DISABLE_SERVER = "true"
  KEEP_JOB_DIR = "false"
  NUM_WORKERS = "4"
  RUST_LOG = "info"
  WORKER_GROUP = "native"

[[mounts]]
  source = "worker_cache"
  destination = "/tmp/windmill/cache"
  auto_extend_size_threshold = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
