# fly.toml app configuration file generated for xxx-windmill-worker on 2023-08-02T21:33:35+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "njiuko-windmill-worker"
primary_region = "fra"

[build]
image = "ghcr.io/windmill-labs/windmill-ee:1.376.0"

[env]
BASE_URL = "https://njiuko-windmill-server.fly.dev/"
DISABLE_SERVER = "true"
KEEP_JOB_DIR = "false"
NUM_WORKERS = "1"
RUST_LOG = "info"

[[mounts]]
source = "worker_cache"
destination = "/tmp/windmill/cache"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 2048
